
#ifndef dragonpoop_model_component_type_h
#define dragonpoop_model_component_type_h

#define model_component_type_vertex 1
#define model_component_type_triangle 2
#define model_component_type_triangle_vertex 3
#define model_component_type_group 4
#define model_component_type_material 5
#define model_component_type_animation 6
#define model_component_type_frame 7
#define model_component_type_joint 8
#define model_component_type_animation_frame 9
#define model_component_type_frame_joint 10
#define model_component_type_vertex_joint 11
#define model_component_type_instance 12
#define model_component_type_vertex_instance 13
#define model_component_type_triangle_vertex_instance 14
#define model_component_type_triangle_instance 15
#define model_component_type_group_instance 16
#define model_component_type_animation_instance 17
#define model_component_type_frame_instance 18
#define model_component_type_animation_frame_instance 19

#define model_component_type_joint_instance 20
#define model_component_type_frame_joint_instance 21
#define model_component_type_vertex_joint_instance 22

#endif